#ifndef BPE_H
#define BPE_H

#ifdef __cplusplus
extern "C" {
#endif

/*
 * BPE text decoder.
 *
 * bpe_print() decompresses a BPE-encoded string (terminated with 0xFF)
 * and outputs it character by character via print().
 *
 * Compressed strings are generated by tools/bpe_compress.py into
 * assets/bpe_texts.h / assets/bpe_texts.c.
 * The merge table lives in assets/bpe_table.h / assets/bpe_table.c.
 */
void bpe_print(const unsigned char *data);

#ifdef __cplusplus
}
#endif

#endif /* BPE_H */
