#ifndef BPE_TABLE_H
#define BPE_TABLE_H

#ifdef __cplusplus
extern "C" {
#endif

/*
 * BPE decoder tables (generated by tools/bpe_compress.py).
 *
 * Encoding:
 *   0 .. BPE_NUM_LITERALS-1   literal ids  -> bpe_remap[id] gives the real char
 *   BPE_NUM_LITERALS .. 0xFE  BPE tokens   -> bpe_table[tok-BPE_NUM_LITERALS]
 *   0xFF                      end of string
 */
#define BPE_NUM_LITERALS  70U
#define BPE_NUM_RULES     184U
#define BPE_TOKEN_BASE    BPE_NUM_LITERALS
#define BPE_END_MARKER    0xFFU

/* bpe_remap[id] == the actual ASCII/Latin-1 byte for literal id */
extern const unsigned char bpe_remap[BPE_NUM_LITERALS];

/* bpe_table[i] == {left_child, right_child} for token (BPE_NUM_LITERALS + i) */
extern const unsigned char bpe_table[BPE_NUM_RULES][2];

#ifdef __cplusplus
}
#endif

#endif /* BPE_TABLE_H */
